export const ui_langs = [
   "nob", "eng", "fin", "rus", "sme"
];

export const ui_langs_long = {
    nob: "Norsk Bokmål",
    eng: "English",
    sme: "Davvisámegillii",
    fin: "Suomeksi",
    rus: "Русский"
};

export const tool_langs = [
"sme",
"fin",
"sms",
"sma",
"mdf",
"bxr",
"chr",
"ciw",
"cor",
"crk",
"deu",
"est",
"evn",
"fao",
"fit",
"fkv",
"gle",
"hdn",
"hun",
"ipk",
"izh",
"kal",
"kca",
"koi",
"kom",
"kpv",
"lav",
"liv",
"lut",
"mhr",
"mns",
"mrj",
"myv",
"nio",
"nno",
"nob",
"olo",
"rmf",
"rup",
"rus",
"sjd",
"sje",
"smj",
"smn",
"som",
"swe",
"udm",
"vep",
"vot",
"vro",
"yrk",
];

export const tool_lang_star = {
    "sme": "gold",
    "fin": "gold",
    "sms": "gold",
    "sma": "gold",
    "mdf": "gold",
    "bxr": "gold",
    "chr": "gold",
    "ciw": "silver",
    "cor": "silver",
    "crk": "silver",
    "deu": "silver",
    "est": "silver",
    "evn": "silver",
    "fao": "silver",
    "fit": "silver",
    "fkv": "silver",
    "gle": "silver",
    "hdn": "silver",
    "hun": "silver",
    "ipk": "bronze",
    "izh": "bronze",
    "kal": "bronze",
    "kca": "bronze",
    "koi": "bronze",
    "kom": "bronze",
    "kpv": "bronze",
    "lav": "bronze",
    "liv": "bronze",
    "lut": "bronze",
    "mhr": "bronze",
    "mns": "bronze",
    "mrj": "bronze",
    "myv": "bronze",
    "nio": "bronze",
    "nno": "bronze",
    "nob": "bronze",
    "olo": "bronze",
    "rmf": "bronze",
    "rup": "bronze",
    "rus": "bronze",
    "sjd": "bronze",
    "sje": "bronze",
    "smj": "bronze",
    "smn": "bronze",
    "som": "bronze",
    "swe": "bronze",
    "udm": "bronze",
    "vep": "bronze",
    "vot": "bronze",
    "vro": "bronze",
    "yrk": "bronze",
}
